apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"config.openshift.io/v1","kind":"OAuth","metadata":{"annotations":{},"name":"cluster"},"spec":{"identityProviders":[{"htpasswd":{"fileData":{"name":"htpass-secret"}},"mappingMethod":"claim","name":"developer","type":"HTPasswd"}],"templates":{"login":{"name":"login-template"}},"tokenConfig":{"accessTokenMaxAgeSeconds":0}}}
    release.openshift.io/create-only: "true"
  creationTimestamp: "2024-06-26T12:39:16Z"
  generation: 2
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: a73cbaa6-40d3-4694-9b98-c0a6eed45825
  resourceVersion: "17998"
  uid: 1a026d88-1ca9-4a31-b409-d3f68fa7b5a3
spec:
  identityProviders:
  - htpasswd:
      fileData:
        name: htpass-ex280
    mappingMethod: claim
    name: htpass-identity-ex280
    type: HTPasswd
  templates:
    login:
      name: login-template
  tokenConfig:
    accessTokenMaxAgeSeconds: 0
