apiVersion: v1
kind: Pod
metadata: 
  name: localvol
spec:
  containers:
  - name: sleepy
    image: busybox
    command:
      - sleep
      - "3600" 
    volumeMounts:
      - mountPath: /data
        name: test
  - name: busy
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
      - mountPath: /data
        name: test
  volumes: 
    - name: test
      emptyDir: {}
