kind: Pod
apiVersion: v1
metadata:
   name: pv-pod
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: pv-claim
  containers:
    - name: pv-container
      image: bitnami/nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: pv-storage
